# Generated by Django 2.2 on 2020-03-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderjobs',
            table='df_order_jobs',
        ),
    ]
