# Generated by Django 2.2 on 2020-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200328_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=20, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='address',
            name='addr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='个人介绍'),
        ),
    ]
