# Generated by Django 2.2 on 2020-03-19 10:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('url', models.CharField(max_length=256, verbose_name='活动链接')),
                ('name', models.CharField(max_length=20, verbose_name='活动名称')),
                ('image', models.ImageField(upload_to='jobs', verbose_name='图片路径')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
            ],
            options={
                'verbose_name': '主页促销活动',
                'verbose_name_plural': '主页促销活动',
                'db_table': 'df_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='JobsSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='岗位SPU名称')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='岗位详情')),
            ],
            options={
                'verbose_name': '岗位SPU',
                'verbose_name_plural': '岗位SPU',
                'db_table': 'df_jobs_spu',
            },
        ),
        migrations.CreateModel(
            name='JobsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='种类名称')),
                ('logo', models.CharField(max_length=20, verbose_name='标识')),
                ('image', models.ImageField(upload_to='type', verbose_name='岗位类型图片')),
            ],
            options={
                'verbose_name': '职位种类',
                'verbose_name_plural': '职位种类',
                'db_table': 'df_jobs_type',
            },
        ),
        migrations.CreateModel(
            name='JobsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='岗位名称')),
                ('desc', models.CharField(max_length=256, verbose_name='岗位简介')),
                ('education', models.CharField(max_length=20, verbose_name='教育程度')),
                ('company', models.CharField(max_length=20, verbose_name='岗位单位')),
                ('Size', models.CharField(max_length=20, verbose_name='单位规模')),
                ('financeStage', models.CharField(max_length=20, verbose_name='单位类型')),
                ('industryField', models.CharField(max_length=20, verbose_name='行业领域')),
                ('salary', models.IntegerField(verbose_name='职薪')),
                ('city', models.CharField(max_length=20, verbose_name='岗位地点')),
                ('workYear', models.CharField(max_length=20, verbose_name='岗位年限')),
                ('stock', models.IntegerField(default=1, verbose_name='岗位库存')),
                ('number', models.IntegerField(default=0, verbose_name='招聘人数')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='岗位状态')),
                ('jobs_spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobsSPU', verbose_name='岗位SPU')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobsType', verbose_name='岗位种类')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'db_table': 'df_jobs_sku',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeJobsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('display_type', models.SmallIntegerField(choices=[(0, '标题'), (1, '图片')], default=1, verbose_name='岗位显示方式')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobsSKU', verbose_name='岗位')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobsType', verbose_name='岗位类型')),
            ],
            options={
                'verbose_name': '主页分类展示岗位',
                'verbose_name_plural': '主页分类展示岗位',
                'db_table': 'df_index_type_jobs',
            },
        ),
        migrations.CreateModel(
            name='IndexJobsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobsSKU', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '首页轮播图片',
                'verbose_name_plural': '首页轮播图片',
                'db_table': 'df_index_banner',
            },
        ),
    ]
