# Generated by Django 2.2 on 2020-03-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobssku',
            old_name='desc',
            new_name='jobDes',
        ),
        migrations.RenameField(
            model_name='jobssku',
            old_name='name',
            new_name='positionName',
        ),
    ]
