# Generated by Django 2.2 on 2020-03-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200320_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobssku',
            old_name='jobDes',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='jobssku',
            old_name='positionName',
            new_name='name',
        ),
    ]
