# Generated by Django 2.2 on 2020-03-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200320_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobssku',
            old_name='Size',
            new_name='companySize',
        ),
        migrations.RenameField(
            model_name='jobssku',
            old_name='desc',
            new_name='jobDes',
        ),
        migrations.RenameField(
            model_name='jobssku',
            old_name='name',
            new_name='positionName',
        ),
        migrations.AddField(
            model_name='jobssku',
            name='positionType',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='岗位种类'),
        ),
    ]
