# Generated by Django 2.2 on 2020-03-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200320_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexjobsbanner',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='indexjobsbanner',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='indexjobsbanner',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='indextypejobsbanner',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='indextypejobsbanner',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='indextypejobsbanner',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='jobs_spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobsSPU', verbose_name='岗位SPU'),
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobsType', verbose_name='岗位种类'),
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='jobsspu',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jobsspu',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='jobsspu',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='jobstype',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jobstype',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='jobstype',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
