# Generated by Django 2.2 on 2020-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20200320_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobssku',
            name='stock',
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='number',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='招聘人数'),
        ),
        migrations.AlterField(
            model_name='jobssku',
            name='salary',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职薪'),
        ),
    ]
