# Generated by Django 2.2 on 2020-03-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200320_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobssku',
            name='jobs_spu',
        ),
        migrations.RemoveField(
            model_name='jobssku',
            name='type',
        ),
    ]
